services:
  - type: web
    name: embz-designz-frontend
    runtime: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_BACKEND_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
